services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - ./config:/config
      - ./tvseries:/tv
      - ./movies:/movies
    restart: unless-stopped
