services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - 9445:80 #map any custom port to use (replace 9445 not 80)
    volumes:
     - ./vw-data:/data:rw
    env_file:
     - ./.env
    environment:
     - SHOW_PASSWORD_HINT=${SHOW_PASSWORD_HINT}
     - ADMIN_TOKEN=${ADMIN_TOKEN}
     - DISABLE_ADMIN_TOKEN=${DISABLE_ADMIN_TOKEN}
     - ROCKET_LIMITS={json=10485760}
     - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
     - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
     - SMTP_HOST=${SMTP_HOST}
     - SMTP_FROM=${SMTP_FROM}
     - SMTP_PORT=${SMTP_PORT}
     - SMTP_SECURITY=${SMTP_SECURITY}
     - SMTP_USERNAME=${SMTP_USERNAME}
     - SMTP_PASSWORD=${SMTP_PASSWORD}
     - DOMAIN=${DOMAIN}
     - LOG_FILE=/data/vaultwarden.log
