services:
    homeassistant:
        image: ghcr.io/home-assistant/home-assistant:stable
        container_name: homeassistant
        devices:
            # rflink
            - /dev/rflink:/dev/ttyUSB1
        volumes:
            - ./hass-config:/config
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro # BT on host: sudo apt install bluez
        restart: unless-stopped
        privileged: true
        network_mode: host
        depends_on:
            - mosquitto
            - zwave-js-ui
            - zigbee2mqtt
    nodered:
        container_name: nodered
        image: nodered/node-red
        environment:
          - TZ=Europe/Copenhagen
        ports:
          - 1880:1880
        volumes:
          - ./nodered:/data
        depends_on:
          - homeassistant
          - mosquitto
        restart: unless-stopped
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        environment:
          - TZ=Europe/Copenhagen
        ports:
          - 1883:1883
          - 9002:9002
        volumes:
          - ./mosquitto/config:/mosquitto/config
          - ./mosquitto/data:/mosquitto/data
          - ./mosquitto/log:/mosquitto/log
        restart: unless-stopped
    code-server:
        container_name: code_server
        image: lscr.io/linuxserver/code-server:latest
        environment:
            - TZ=Europe/Copenhagen
            - DEFAULT_WORKSPACE=/config
        ports:
            - 8443:8443
        volumes:
            - ./hass-config:/config
        restart: unless-stopped
    zwave-js-ui:
        restart: unless-stopped
        ports:
            - 8091:8091
            - 3000:3000
        devices:
            # zwave
            - /dev/zw090:/dev/ttyUSB0
        volumes:
            - ./zwavejsui:/usr/src/app/store
        environment:
            - TZ=Europe/Copenhagen
            - SESSION_SECRET=REDACTED
            - PGID=1000
            - PUID=1000
            - FORCE_DISABLE_SSL=false
        image: zwavejs/zwave-js-ui:latest
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        volumes:
            - ./zigbee2mqtt-data:/app/data
            - /run/udev:/run/udev:ro
        devices:
            # CC251
            # - /dev/cc2531:/dev/ttyACM1
            # CC2652
            - /dev/cc2652:/dev/ttyACM1
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            - TZ=Europe/Copenhagen
        depends_on:
            - mosquitto
